# Generated by Django 3.1.7 on 2022-11-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20210912_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_unit',
            field=models.IntegerField(default=0),
        ),
    ]
